name: girixscanner
description: A PDF Creator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  font_awesome_flutter: ^8.8.1

  pdf: ^1.9.0
  pdf_render: ^0.64.0

  google_fonts: ^1.1.0
  scoped_model: ^1.0.1
  email_validator: ^1.0.0
  shared_preferences: ^0.5.7+3

  barcode_widget: ^1.3.0
  barcode: ^1.13.0
  barcode_scan: ^3.0.1
  barcode_image: ^1.0.3
  qr_flutter: ^3.1.0

  image: ^2.1.12
  image_cropper: ^1.3.0
  photofilters: ^2.0.1
  image_picker: ^0.6.7+4
  edge_detection: ^1.0.5
  printing: ^3.5.0

  share: ^0.6.4+3
  wc_flutter_share: ^0.2.2

  open_file: ^3.0.1
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1

  sqflite: ^1.3.0

  simple_animations: ^2.2.1
  flutter_circle_color_picker: ^0.2.0


#  cloud_firestore: ^0.13.7
#  firebase_auth: ^0.16.1
#  firebase_storage: ^3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/gs_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/gs_logo.png
    - assets/images/review.png
    - assets/images/empty.png
    - assets/images/warning.png
    - assets/images/server_down.png
    - assets/images/image-resize.png
    - assets/images/my_personal_files.png
    - assets/images/organize_photos.png
    - assets/images/reviewed_docs_neeb.png
    - assets/images/profile_pic.png
    - assets/files/AttestationForm.pdf

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
